### ISSUE TITLE
HTML Language

### ISSUE THREAD

**Issue by lucascurti** [VismaLietuva/vscode-angular-support#3]
Seems it's only working when the language is setup as HTML. If the chosen language is "Angular Template" it doesn't work.

PS. Awesome extension!

**Comment by dzonatan** [comment]
Please provide url to the extension which adds "Angular Template" as a language option.
Thanks! 🍻

**Comment by lucascurti** [comment]
I'm kind of a newbie when talking about VSCode and Angular but I think the extension that added the language is this one: https://goo.gl/3NsWvp

Not sure if this is something common but I also sometimes use the Handlebars languages to get the curly braces highlight. Do you think it might be a good idea to make it work with Handlebars, too?

**Comment by dzonatan** [comment]
`vscode-ng-language-service` tries to solve the same thing (language support for angular). 
Just this one intent to be a lot more lightweight = faster.

So you have to choose one to use.

**Comment by lucascurti** [comment]
I see... I wasn't able to make it work anyway so I'll keep yours. One thing I was interested on ```vscode-ng-language-service``` was the fact that, apparently, it adds intellisense/autocomplete for properties and methods on the HTML template. Is that something that you are also planning to add on this extension?
